/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0jW5SvhbsMJ
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { SelectValue, SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"

export function Component() {
  return (
    <section className="w-full h-screen bg-gray-100 dark:bg-gray-900 flex items-center justify-center p-10 lg:p-0">
      <div className="bg-white max-w-md mx-auto rounded-xl shadow-md overflow-hidden md:max-w-2xl dark:bg-gray-800">
        <div className="md:flex">
          <div className="md:flex-shrink-0">
            <img
              alt="Login Image"
              className="h-48 w-full object-cover md:w-48 md:h-full md:rounded-none rounded-t-xl"
              height="299"
              src="/placeholder.svg"
              style={{
                aspectRatio: "448/299",
                objectFit: "cover",
              }}
              width="448"
            />
          </div>
          <div className="p-8">
            <div className="uppercase tracking-wide text-sm text-indigo-500 font-semibold">Login</div>
            <div className="block mt-1 text-lg leading-tight font-medium text-black dark:text-white">Welcome back!</div>
            <p className="mt-2 text-gray-500 dark:text-gray-400">Log in to your account to continue.</p>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="m@example.com" required type="email" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <Input id="password" required type="password" />
              </div>
              <Button className="w-full" type="submit">
                Login
              </Button>
            </div>
            <div className="mt-6 flex justify-between">
              <Link
                className="inline-block text-sm text-gray-600 hover:text-gray-900 dark:text-white dark:hover:text-gray-200"
                href="#"
              >
                Forgot your password?
              </Link>
              <Link
                className="inline-block text-sm text-gray-600 hover:text-gray-900 dark:text-white dark:hover:text-gray-200"
                href="#"
              >
                Don't have an account? Register
              </Link>
            </div>
            <div className="mt-6">
              <Badge className="inline-block bg-blue-100 text-blue-800 px-2 py-1 text-xs font-semibold tracking-wider rounded-full dark:bg-blue-800 dark:text-blue-100">
                Language: English
              </Badge>
              <Select>
                <SelectTrigger className="mt-2">
                  <SelectValue placeholder="Change language" />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectItem value="english">English</SelectItem>
                    <SelectItem value="spanish">Spanish</SelectItem>
                    <SelectItem value="french">French</SelectItem>
                    <SelectItem value="german">German</SelectItem>
                    <SelectItem value="italian">Italian</SelectItem>
                  </SelectGroup>
                </SelectContent>
              </Select>
            </div>
            <div className="mt-6">
              <div className="flex items-center">
                <div className="text-gray-700 dark:text-gray-300 mr-2">Dark mode</div>
                <div className="relative inline-block w-10 align-middle select-none transition duration-200 ease-in">
                  <input
                    className="toggle-checkbox absolute block w-6 h-6 rounded-full bg-white border-4 appearance-none cursor-pointer"
                    id="toggle"
                    name="toggle"
                    type="checkbox"
                  />
                  <label
                    className="toggle-label block overflow-hidden h-6 rounded-full bg-gray-300 cursor-pointer"
                    htmlFor="toggle"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
